/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Listas.ListaEnlazada;
import javax.swing.JOptionPane;
import vista.modeloTablas.ModeloTablaFloat;

/**
 *
 * @author Iván González
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private ModeloTablaFloat mtf = new ModeloTablaFloat();
    private ListaEnlazada<Float> lista = new ListaEnlazada<>();
    
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        cargarTablaSinOrdenar();
        ocultarPanelOrdenamiento();
        setLocationRelativeTo(this);
    }
    
    private void cargarTablaSinOrdenar(){
        mtf.setLista(lista);
        tblSinOrdenar.setModel(mtf);
        tblSinOrdenar.updateUI();
    }
    
    private void cargarTablaOrdenada(){
        mtf.setLista(lista);
        tblOrdenada.setModel(mtf);
        tblOrdenada.updateUI();
    }
    
    private void limpiar(){
        cargarTablaSinOrdenar();
        txtNroDatos.setText("");
    }
    
    private void ocultarPanelOrdenamiento(){
        jPanel4.setVisible(false);
    }
    
    private void mostrarPanelOrdenamiento(){
        jPanel4.setVisible(true);
    }

    private void crearLista(){
        if(txtNroDatos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el tamaño de la lista", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            lista.generarLista(Integer.parseInt(txtNroDatos.getText()));
            cargarTablaSinOrdenar();
            cargarTablaOrdenada();
            limpiar();
            btnCrear.setEnabled(false);
            txtNroDatos.setEditable(false);
            mostrarPanelOrdenamiento();
        }
    }
    
    private void ordenarLista() throws Exception{
        if(cbxMetodoOrden.getSelectedItem().toString().equalsIgnoreCase("ShellSort")){
            if(cbxTipoOrden.getSelectedItem().toString().equalsIgnoreCase("Ascendente")){
                lista.ordenarShellSort(null, 2);
                cargarTablaOrdenada();
//                btnOrdenar.setEnabled(false);
            } else {
                lista.ordenarShellSort(null, 1);
                cargarTablaOrdenada();
//                btnOrdenar.setEnabled(false);
            }
        } else {
            if(cbxTipoOrden.getSelectedItem().toString().equalsIgnoreCase("Ascendente")){
                lista.ordenarQuickSort(null, 2);
                cargarTablaOrdenada();
//                btnOrdenar.setEnabled(false);
            } else {
                lista.ordenarQuickSort(null, 1);
                cargarTablaOrdenada();
//                btnOrdenar.setEnabled(false);
            }
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNroDatos = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSinOrdenar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrdenada = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxMetodoOrden = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbxTipoOrden = new javax.swing.JComboBox<>();
        btnOrdenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generar Lista"));
        jPanel2.setLayout(null);

        jLabel1.setText("Número de datos de la lista:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 30, 160, 20);
        jPanel2.add(txtNroDatos);
        txtNroDatos.setBounds(180, 30, 100, 22);

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel2.add(btnCrear);
        btnCrear.setBounds(100, 70, 72, 22);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabla"));
        jPanel3.setLayout(null);

        tblSinOrdenar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSinOrdenar);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 40, 280, 280);

        tblOrdenada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblOrdenada);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(300, 40, 300, 280);

        jLabel4.setText("Lista desordenada");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(90, 20, 110, 16);

        jLabel5.setText("Lista ordenada");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(410, 20, 90, 16);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar Lista"));
        jPanel4.setLayout(null);

        jLabel2.setText("Método de ordenamiento:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 20, 150, 20);

        cbxMetodoOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ShellSort", "QuickSort" }));
        jPanel4.add(cbxMetodoOrden);
        cbxMetodoOrden.setBounds(170, 20, 130, 22);

        jLabel3.setText("Tipo de orden:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 50, 150, 20);

        cbxTipoOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        jPanel4.add(cbxTipoOrden);
        cbxTipoOrden.setBounds(170, 50, 130, 22);

        btnOrdenar.setText("ORDENAR");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });
        jPanel4.add(btnOrdenar);
        btnOrdenar.setBounds(110, 80, 90, 22);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        crearLista();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        // TODO add your handling code here:
        
        try {
            ordenarLista();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.JComboBox<String> cbxMetodoOrden;
    private javax.swing.JComboBox<String> cbxTipoOrden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblOrdenada;
    private javax.swing.JTable tblSinOrdenar;
    private javax.swing.JTextField txtNroDatos;
    // End of variables declaration//GEN-END:variables
}
